---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - git
          - curl
          - unzip
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
