# ==========================================================
# IONOS CI/CD Infrastructure Demo
#
# Ansible inventory file
#
# Defines the servers managed by Ansible.
#
# ==========================================================


# Deployment target group
#
# Servers listed here will receive application updates
# through the CI/CD pipeline.

[ionos]


# IONOS Cloud Ubuntu server
#
# Connection details:
# - Public IP address
# - SSH user for remote administration

212.227.233.122 ansible_user=ubuntu
